package openapi

import (
	"bytes"
	"go/ast"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestParseHandlersReportsMissingRouter(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "handler.go"), `package handler

// @Summary Missing router
// @Success 200 {object} dto.UserResponse "OK"
func MissingRouter() {}
`)

	_, err := ParseHandlers(dir, emptyRegistry())
	if err == nil || !strings.Contains(err.Error(), "missing @Router") {
		t.Fatalf("ParseHandlers() error = %v, want missing @Router", err)
	}
}

func TestParseHandlersReportsUnsupportedMethod(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "handler.go"), `package handler

// @Summary Unsupported method
// @Success 200 {object} dto.UserResponse "OK"
// @Router /demo [trace]
func UnsupportedMethod() {}
`)

	_, err := ParseHandlers(dir, emptyRegistry())
	if err == nil || !strings.Contains(err.Error(), "unsupported method") {
		t.Fatalf("ParseHandlers() error = %v, want unsupported method", err)
	}
}

func TestParseHandlersReportsDuplicateOperation(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "handler.go"), `package handler

// @Summary First
// @Success 200 {object} dto.UserResponse "OK"
// @Router /demo [get]
func First() {}

// @Summary Second
// @Success 200 {object} dto.UserResponse "OK"
// @Router /demo [get]
func Second() {}
`)

	_, err := ParseHandlers(dir, emptyRegistry())
	if err == nil || !strings.Contains(err.Error(), "duplicate operation") {
		t.Fatalf("ParseHandlers() error = %v, want duplicate operation", err)
	}
}

func TestParseHandlersSupportsArraySuccessResponses(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "handler.go"), `package handler

// @Summary List
// @Success 200 {array} dto.UserResponse "OK"
// @Router /demo [get]
func List() {}
`)

	operations, err := ParseHandlers(dir, emptyRegistryWithStruct("UserResponse"))
	if err != nil {
		t.Fatalf("ParseHandlers() error = %v", err)
	}
	if len(operations) != 1 || len(operations[0].Responses) != 1 {
		t.Fatalf("operations = %#v", operations)
	}
	schema := operations[0].Responses[0].Schema
	if schema == nil || schema.Type != "array" || schema.Items == nil || schema.Items.Ref != "#/components/schemas/UserResponse" {
		t.Fatalf("response schema = %#v, want UserResponse array", schema)
	}
}

func TestLoadSchemasInfersJSONBindingAndTimeFields(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, filepath.Join(dir, "dto.go"), "package dto\n\n"+
		"import \"time\"\n\n"+
		"type Sample struct {\n"+
		"\tName string `json:\"name\" binding:\"required,min=3,max=32\"`\n"+
		"\tEmail string `json:\"email\" binding:\"required,email\"`\n"+
		"\tTags []string `json:\"tags\"`\n"+
		"\tPublishedAt *time.Time `json:\"published_at,omitempty\"`\n"+
		"}\n")

	registry, err := LoadSchemas(dir)
	if err != nil {
		t.Fatalf("LoadSchemas() error = %v", err)
	}
	schema := registry.Schemas()["Sample"]
	if schema == nil {
		t.Fatal("Sample schema is nil")
	}
	if got := strings.Join(schema.Required, ","); got != "email,name" {
		t.Fatalf("required = %q, want email,name", got)
	}
	name := findProperty(schema, "name")
	if name == nil || name.MinLength == nil || *name.MinLength != 3 || name.MaxLength == nil || *name.MaxLength != 32 {
		t.Fatalf("name schema = %#v, want minLength 3 and maxLength 32", name)
	}
	email := findProperty(schema, "email")
	if email == nil || email.Format != "email" {
		t.Fatalf("email schema = %#v, want email format", email)
	}
	tags := findProperty(schema, "tags")
	if tags == nil || tags.Type != "array" || tags.Items == nil || tags.Items.Type != "string" {
		t.Fatalf("tags schema = %#v, want string array", tags)
	}
	publishedAt := findProperty(schema, "published_at")
	if publishedAt == nil || publishedAt.Type != "string" || publishedAt.Format != "date-time" || !publishedAt.Nullable {
		t.Fatalf("published_at schema = %#v, want nullable date-time", publishedAt)
	}
}

func TestGenerateUsesCurrentHandlersAndIsStable(t *testing.T) {
	root := repoRoot(t)
	config := Config{
		HandlerDir: filepath.Join(root, DefaultHandlerDir),
		DTODir:     filepath.Join(root, DefaultDTODir),
	}

	first, err := Generate(config)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	second, err := Generate(config)
	if err != nil {
		t.Fatalf("Generate() second error = %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("Generate() output is not stable")
	}
	text := string(first)
	for _, want := range []string{
		"# Code generated by go run ./cmd/openapi generate; DO NOT EDIT.",
		"openapi: 3.0.3",
		"/plugins/registrations:",
		"/plugins/{plugin_key}:",
		"PluginRegistrationRequest:",
		"securitySchemes:",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated spec does not contain %q", want)
		}
	}
}

func TestGenerateFileCheck(t *testing.T) {
	root := repoRoot(t)
	output := filepath.Join(t.TempDir(), "openapi.yaml")
	config := Config{
		HandlerDir: filepath.Join(root, DefaultHandlerDir),
		DTODir:     filepath.Join(root, DefaultDTODir),
		Output:     output,
	}
	if err := GenerateFile(config); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}
	config.Check = true
	if err := GenerateFile(config); err != nil {
		t.Fatalf("GenerateFile(check) error = %v", err)
	}
	if err := os.WriteFile(output, []byte("stale\n"), 0o644); err != nil {
		t.Fatalf("write stale output: %v", err)
	}
	if err := GenerateFile(config); err == nil || !strings.Contains(err.Error(), "out of date") {
		t.Fatalf("GenerateFile(check stale) error = %v, want out of date", err)
	}
}

func emptyRegistry() *SchemaRegistry {
	return &SchemaRegistry{
		structs: map[string]*ast.StructType{},
		schemas: map[string]*Schema{},
	}
}

func emptyRegistryWithStruct(name string) *SchemaRegistry {
	registry := emptyRegistry()
	registry.structs[name] = &ast.StructType{}
	return registry
}

func findProperty(schema *Schema, name string) *Schema {
	for _, property := range schema.Properties {
		if property.Name == name {
			return property.Schema
		}
	}
	return nil
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", ".."))
	return root
}

func writeTestFile(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
