package openapi

import (
	"sort"
	"strconv"
	"strings"
)

func MarshalYAML(doc Document) []byte {
	var b strings.Builder
	b.WriteString("# Code generated by go run ./cmd/openapi generate; DO NOT EDIT.\n")
	b.WriteString("openapi: 3.0.3\n")
	b.WriteString("info:\n")
	writeLine(&b, 1, "title: "+quote(doc.Title))
	writeLine(&b, 1, "version: "+quote(doc.Version))
	b.WriteString("servers:\n")
	writeLine(&b, 1, "- url: "+quote(doc.BasePath))
	b.WriteString("paths:\n")
	for _, path := range sortedPathKeys(doc.Paths) {
		writeLine(&b, 1, path+":")
		methods := doc.Paths[path]
		for _, method := range sortedOperationMethods(methods) {
			writeOperation(&b, 2, method, methods[method])
		}
	}
	b.WriteString("components:\n")
	writeSchemas(&b, 1, doc.Schemas)
	writeLine(&b, 1, "securitySchemes:")
	writeLine(&b, 2, "bearerAuth:")
	writeLine(&b, 3, "type: http")
	writeLine(&b, 3, "scheme: bearer")
	writeLine(&b, 3, "bearerFormat: JWT")
	return []byte(b.String())
}

func writeOperation(b *strings.Builder, indent int, method string, operation Operation) {
	writeLine(b, indent, method+":")
	if len(operation.Tags) > 0 {
		writeLine(b, indent+1, "tags:")
		for _, tag := range operation.Tags {
			writeLine(b, indent+2, "- "+quote(tag))
		}
	}
	if operation.Summary != "" {
		writeLine(b, indent+1, "summary: "+quote(operation.Summary))
	}
	if operation.Description != "" {
		writeLine(b, indent+1, "description: "+quote(operation.Description))
	}
	if len(operation.Security) > 0 {
		writeLine(b, indent+1, "security:")
		for _, scheme := range operation.Security {
			writeLine(b, indent+2, "- "+scheme+": []")
		}
	}
	if len(operation.Parameters) > 0 {
		writeLine(b, indent+1, "parameters:")
		for _, parameter := range operation.Parameters {
			writeLine(b, indent+2, "- name: "+quote(parameter.Name))
			writeLine(b, indent+3, "in: "+parameter.In)
			writeLine(b, indent+3, "required: "+strconv.FormatBool(parameter.Required))
			if parameter.Description != "" {
				writeLine(b, indent+3, "description: "+quote(parameter.Description))
			}
			writeLine(b, indent+3, "schema:")
			writeSchema(b, indent+4, parameter.Schema)
		}
	}
	if operation.RequestBody != nil {
		writeLine(b, indent+1, "requestBody:")
		writeLine(b, indent+2, "required: "+strconv.FormatBool(operation.RequestBody.Required))
		if operation.RequestBody.Description != "" {
			writeLine(b, indent+2, "description: "+quote(operation.RequestBody.Description))
		}
		writeLine(b, indent+2, "content:")
		for _, mime := range contentTypes(operation.Accepts) {
			writeLine(b, indent+3, mime+":")
			writeLine(b, indent+4, "schema:")
			writeSchema(b, indent+5, operation.RequestBody.Schema)
		}
	}
	writeLine(b, indent+1, "responses:")
	for _, response := range operation.Responses {
		writeLine(b, indent+2, quote(response.Code)+":")
		writeLine(b, indent+3, "description: "+quote(response.Description))
		writeLine(b, indent+3, "content:")
		for _, mime := range contentTypes(operation.Produces) {
			writeLine(b, indent+4, mime+":")
			writeLine(b, indent+5, "schema:")
			writeResponseBodySchema(b, indent+6, response.Schema)
		}
	}
}

func writeResponseBodySchema(b *strings.Builder, indent int, data *Schema) {
	writeLine(b, indent, "type: object")
	writeLine(b, indent, "required:")
	writeLine(b, indent+1, "- code")
	writeLine(b, indent+1, "- msg")
	writeLine(b, indent, "properties:")
	writeLine(b, indent+1, "code:")
	writeLine(b, indent+2, "type: integer")
	writeLine(b, indent+2, "format: int32")
	writeLine(b, indent+1, "msg:")
	writeLine(b, indent+2, "type: string")
	if data != nil {
		writeLine(b, indent+1, "data:")
		writeSchema(b, indent+2, data)
	}
}

func writeSchemas(b *strings.Builder, indent int, schemas map[string]*Schema) {
	writeLine(b, indent, "schemas:")
	for _, name := range sortedSchemaKeys(schemas) {
		writeLine(b, indent+1, name+":")
		writeSchema(b, indent+2, schemas[name])
	}
}

func writeSchema(b *strings.Builder, indent int, schema *Schema) {
	if schema == nil {
		writeLine(b, indent, "type: object")
		return
	}
	if schema.Ref != "" {
		writeLine(b, indent, "$ref: "+quote(schema.Ref))
		return
	}
	if schema.Type != "" {
		writeLine(b, indent, "type: "+schema.Type)
	}
	if schema.Format != "" {
		writeLine(b, indent, "format: "+schema.Format)
	}
	if schema.Nullable {
		writeLine(b, indent, "nullable: true")
	}
	if schema.MinLength != nil {
		writeLine(b, indent, "minLength: "+strconv.Itoa(*schema.MinLength))
	}
	if schema.MaxLength != nil {
		writeLine(b, indent, "maxLength: "+strconv.Itoa(*schema.MaxLength))
	}
	if schema.Minimum != nil {
		writeLine(b, indent, "minimum: "+strconv.Itoa(*schema.Minimum))
	}
	if schema.Maximum != nil {
		writeLine(b, indent, "maximum: "+strconv.Itoa(*schema.Maximum))
	}
	if schema.Items != nil {
		writeLine(b, indent, "items:")
		writeSchema(b, indent+1, schema.Items)
	}
	if len(schema.Required) > 0 {
		writeLine(b, indent, "required:")
		for _, required := range schema.Required {
			writeLine(b, indent+1, "- "+required)
		}
	}
	if len(schema.Properties) > 0 {
		writeLine(b, indent, "properties:")
		for _, property := range schema.Properties {
			writeLine(b, indent+1, property.Name+":")
			writeSchema(b, indent+2, property.Schema)
		}
	}
}

func writeLine(b *strings.Builder, indent int, line string) {
	b.WriteString(strings.Repeat("  ", indent))
	b.WriteString(line)
	b.WriteByte('\n')
}

func quote(value string) string {
	return strconv.Quote(value)
}

func contentTypes(values []string) []string {
	if len(values) == 0 {
		return []string{"application/json"}
	}
	result := append([]string(nil), values...)
	sort.Strings(result)
	return result
}

func sortedPathKeys(paths map[string]map[string]Operation) []string {
	keys := make([]string, 0, len(paths))
	for key := range paths {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedOperationMethods(methods map[string]Operation) []string {
	keys := make([]string, 0, len(methods))
	for key := range methods {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedSchemaKeys(schemas map[string]*Schema) []string {
	keys := make([]string, 0, len(schemas))
	for key := range schemas {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
